apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: kustomizegoat
  name: kustomizegoat
  namespace: kustomizegoat
spec:
  replicas: 2
  selector:
    matchLabels:
      app: kustomizegoat
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: kustomizegoat
    spec:
      containers:
      - image: eurogig/kustomizegoat:0.1
        name: kustomizegoat

