apiVersion: v1
kind: Service
metadata:
  labels:
    app: kustomizegoat
  name: goatlb
  namespace: kustomizegoat
spec:
  ports:
  - name: goatport
    protocol: TCP
    targetPort: 8080
    port: 80
  selector:
    app: kustomizegoat
  type: LoadBalancer
